### ISSUE TITLE
Incompatible version of vue-eslint-parser.

### ISSUE THREAD

**Issue by jpickwell** [nuxt/eslint-plugin-nuxt#21]
`eslint-plugin-vue` currently depends on `vue-eslint-parser@^5.0.0`, however this plugin depends on `vue-eslint-parser@^6.0.2`. This version mismatch causes issues with at least one of `eslint-plugin-vue`'s rules (`vue/attributes-order`).

[`vue-eslint-parser@6.0.0`](https://github.com/mysticatea/vue-eslint-parser/releases/v6.0.0) made a breaking change to one of the AST nodes.

**Comment by clarkdo** [comment]
I’ll fix it

**Comment by clarkdo** [comment]
Fixed int v0.4.3

**Comment by jpickwell** [comment]
Awesome. May want to add the following to `renovate.json`:
```json
"ignoreDeps": ["vue-eslint-parser"]
```

**Comment by clarkdo** [comment]
@jpickwell Thanks for the feed back.

Since eslint-plugin-vue [master](https://github.com/vuejs/eslint-plugin-vue/blob/master/package.json#L49) has upgraded to vue-eslint-parser@6, so it should be released soon, I'll keep an eye the release of `eslint-plugin-vue` and migrate it.
