### ISSUE TITLE
Expected '<component>' elements to have 'v-bind:is' attribute  vue/require-component-is

### ISSUE THREAD

**Issue by matamune94** [nuxt/eslint-plugin-nuxt#73]
maybe update something for fix this error ?
they say use eslint-plugin-vue@6 
https://github.com/vuejs/eslint-plugin-vue/issues/869#issuecomment-553673273

**Comment by manniL** [comment]
Duplicate of https://github.com/nuxt/eslint-plugin-nuxt/issues/65
