### ISSUE TITLE
Error: Cannot find module '@nuxtjs/eslint-module'

### ISSUE THREAD

**Issue by Treen11** [nuxt/eslint-plugin-nuxt#87]
After creating a fresh nuxt app using the create-nuxt-app and selecting the express framework, i am unable to deploy the app to google app engine. When i attempt to deploy the app as is, i encounted this error: "Error: Cannot find module '@nuxtjs/eslint-module'". The problem goes away when i move the @nuxtjs/eslint-modul and @nuxtjs/esling-config from devDependencies to dependencies in package.json.

Could anyone please give me on a hint on what might be the problem? I have tryed everything i could find on google with no luck. Thanks!

**Comment by clarkdo** [comment]
Thanks for the reporting, may I ask if you’re using yarn install —production or NODE_ENV=production when you install?

I think this is an issue from create-nuxt-app, I’ll propose a fix shortly, as a quick fix you can move it to dependencies as you already did or not set production env/flag before install.

**Comment by Treen11** [comment]
Hi, thanks for the answer. Yes i am setting NODE_ENV: 'production' in the environment. I have tryed to set it to 'development' just to try it out and the problem was still there. I am using the recommended app.yaml file from nuxt documentation, which includes the NODE_ENV: 'production' variable: [https://nuxtjs.org/faq/appengine-deployment/](https://nuxtjs.org/faq/appengine-deployment/)

**Comment by Treen11** [comment]
Should i move this issue to the create-nuxt-app repo?

**Comment by clarkdo** [comment]
@Treen11 development should be used before you install the dependencies and build nuxt app, not at gae runtime.

**Comment by Ornhoj** [comment]
I'm having the same issue with nuxt.js@2.11 - it seems like buildModules are included in the request when initiating in production mode.

`@nuxtjs/eslint` is a devDependency and i have the module in my `buildModules` section

This is my install script `cross-env NODE_ENV=production yarn install`

**Comment by clarkdo** [comment]
This is an issue of `buildModules`, I'll discuss with team and fingure out a fix.
